accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='accounts'
urlpatterns = [
    path('',views.home,name='accounts_home'),
    path('register',views.register,name='register'),
    path('profile/',views.red_profile, name='red_profile'),
    path('profile/<int:id>',views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name ='accounts/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='blog'
urlpatterns = [
    path('',views.index, name='index'),
    path('home', views.home, name='home'),
    path('create_post',views.create_post, name='create_post'),
    path('post/<int:id>', views.post_detail, name='post_detail'),
    path('create_comment', views.create_comment, name='create_comment'),
    path('like_post', views.like_post, name='like_post'),

]

features/urls.py
from django.urls import path
from . import views


app_name='features'
urlpatterns = [
    path('users',views.users, name='users'),
    path('suggestions',views.suggestions, name='suggestions'),
    path('news',views.news, name='news'),
    path('announcement',views.announcement, name='announcement'),
]

social/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('', include('blog.urls')),
    path('features/',include('features.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

blog/models.py
from django.db import models
from ckeditor_uploader.fields import RichTextUploadingField
from ckeditor.fields import RichTextField
from django.utils import timezone
from accounts.models import User

# Create your models here.

class Post(models.Model):
    title= models.CharField(max_length=100,null=True, blank=True)
    content=RichTextUploadingField()
    date_posted=models.DateTimeField(default=timezone.now)
    snippet=RichTextField()
    author=models.ForeignKey(User, on_delete=models.CASCADE)
    thumbnail_img= models.ImageField(upload_to='post_pics')

    def __str__(self):
        return self.title

class Comment(models.Model):
    comment= models.TextField()
    date_posted=models.DateTimeField(default= timezone.now)
    writer= models.ForeignKey(User, on_delete= models.CASCADE)
    post= models.ForeignKey(Post, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.post} {self.pk}'

class Likes(models.Model):
    post= models.ForeignKey(Post, on_delete=models.CASCADE)
    liked_users=models.ManyToManyField(User, related_name='liked_users', blank=True)

    def __str__(self):
        return f'{self.post} {self.pk}'

blog/forms.py
from django import forms
from accounts.models import User
from .models import Post, Comment, Likes
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError

class PostForm(forms.ModelForm):

    class Meta:
        model=Post
        fields=['title','content','snippet','thumbnail_img','author']
        exclude=('author',)

class CommentsForm(forms.ModelForm):

    class Meta:
         model= Comment
         fields=['comment','writer','post']
         exclude=('writer','post',)

blog/views.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.http import HttpResponse, FileResponse, JsonResponse
from accounts.models import User
from .forms import PostForm, CommentsForm
from .models import Post, Comment, Likes
from django.utils import timezone
# Create your views here.

def index(request):
    if request.user.is_authenticated:
        return redirect('blog:home')
    else:
        return render(request, 'blog/index.html')

def home(request):
    posts= Post.objects.all().order_by('-date_posted')

    return render(request, 'blog/home.html',{'posts':posts})

def create_post(request):
    if request.method=='POST':
        form =PostForm(request.POST, request.FILES)
        if form.is_valid:
            inst= form.save(commit=False)
            inst.author= request.user
            inst.save()
            Likes.objects.create(post=inst)
            return redirect('blog:home')
    
    else:
        form= PostForm()

    return render(request,'blog/create_post.html',{'form':form})

def post_detail(request, id):
    post = Post.objects.filter(pk=id).first()
    comments= Comment.objects.filter(post=post)
    if comments == None:
        comments=[]
    else:
        comments=comments.all().order_by('-date_posted')
    
    likes= Likes.objects.filter(post=post).first()
    form= CommentsForm()

    return render(request, 'blog/post_detail.html',{'post':post, 'comments':comments,'likes':likes, 'form':form})

def create_comment(request):
    writer=request.user
    id= request.POST['id']
    if request.method=="POST":
        form=CommentsForm(request.POST)
        
        if form.is_valid:
            inst=form.save(commit=False)
            post= Post.objects.filter(pk=id).first()
            inst.post=post
            inst.writer=writer
            inst.save()
        
            return JsonResponse({'date_posted':inst.date_posted, 'comment':str(request.POST['comment'])})
        else:
            return JsonResponse({'done':False}) 

def like_post(request):
    id=int(request.POST['like_id'])
    
    email=request.POST['like_email']
    user=User.objects.filter(email=email).first()
    user_pk=user.pk
    
    post=Post.objects.filter(pk=id).first()
    like_object= Likes.objects.filter(post=post).first()
    liked_users= like_object.liked_users.all()
    trig=0
    for person in liked_users:
        if person==user:
            trig=1
    if trig==0:
        num=len(list(liked_users))
        like_object.liked_users.add(user_pk)
        like_object.save()
        return JsonResponse({'message':f'{user.first_name} {user.last_name} and {num} others'})

    else:
        like_object.liked_users.remove(user_pk)
        like_object.save()
        num=len(list(liked_users))-1
        if num==0:
            return JsonResponse({'message':f'0 likes'})
        else:
            return JsonResponse({'message':f'{liked_users[0].first_name} {liked_users[0].last_name} and {num-1} others'})



    

blog/templates/blog/create_post.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    <div class="container text-center">
                
            <div class="row">
                    
                    <div class="col">
                            <form method='POST' enctype='multipart/form-data' class="mb-3" >
                                <legend class='border-bottom mb-4 display-4'>Create a Post</legend>
                                {% csrf_token %}
                                    <fieldset >
                                        {{form.media}}
                                        {{form|crispy}}
                                    </fieldset>
                                    <div class="mt-3">
                                        <button class='btn btn-outline-info' type ='submit'>POST</button>
                                    </div>
                            </form>
                    </div>
                
            </div>        
            
    </div>   

{% endblock %}

blog/templates/blog/home.html
{% extends 'base.html' %}

{% block content %}

<div class="container mb-4">

    </div>
    <div class="row ml-4">
        <div class="col-md-8 border-right border-secondary">
            
            <div class="border border-secondary rounded mb-4 mr-4 ml-4 pl-4 pt-2 pb-2">
                <h2><a href="{% url 'blog:create_post' %}" class="text-success">Create New Post <b>+</b> </a></h2>
            </div>
            <hr>
            <div class="row mt-4">
                {% for post in posts %}
                    <div class="col-md-6 mb-4">
                            <div class="card h-100">
                                    <a href="{% url 'blog:post_detail' post.pk %}">
                                      <img src="{{ post.thumbnail_img.url }}" class="card-img-top" alt="No image found for thumbanil" style="vertical-align: middle; border-style: none; width: 100%; height: 250px; object-fit: cover;">
                                    </a>
                                    <div class="card-body d-flex flex-column">
                                        <h5 class="card-title"><a href="{% url 'blog:post_detail' post.pk %}">{{ post.title }}</a></h5>
                                        <h6 class="card-subtitle mb-2 text-muted">{{ post.author.first_name }} {{ post.author.last_name }}</h6>
                                        <small class="card-text">{{ post.snippet|safe }}</small>
                                        <a href="{% url 'blog:post_detail' post.pk %}" class="card-link mt-auto">Read More</a>
                                      </div>
                            </div>
                    </div>
                {% endfor %}
            </div>
        </div>
        <div class="col-md-4">
            <div class="border border-secondary rounded m-4 text-center" style="background-color: rgb(243, 245, 247); position: -webkit-sticky;
            position: sticky;top: 20%;">
                <a href="{% url 'features:news' %}" style="font-size: 1.7em;">News</a><hr>
                <a href="{% url 'features:announcement' %}" style="font-size: 1.7em;">Announcements</a><hr>
                <a href="#" style="font-size: 1.7em;">Friends</a><hr>
                <a href="#" style="font-size: 1.7em;">Creator</a>
            </div>
        </div>
    </div>
</div>


{% endblock %}

blog/templates/blog/index.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>SOCIAL</title>
    <style>
            #bg{
                background-size: 1800px 900px;
                background-repeat: no-repeat;
                background-position: top;
                background-attachment: fixed;
            }
    </style>
  </head>
  <body id="bg" style="background-image: url('{% static "images/SOCIAL.png"%}')" >
      
    <div class="container mt-4" style ="display:flex; justify-content:space-around">
        <a href ="{% url 'accounts:register' %}"><h1 class=" display-4 ">JOIN NOW</h1></a>
        <a href ="{% url 'accounts:login' %}"><h1 class=" display-4 ">LOGIN</h1></a>

    </div>

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>

blog/templates/blog/post_detail.html
{% extends 'base.html' %}
{% load blog_filters %}
{% load crispy_forms_tags %}
{% block content %}
<div class="container mb-4">
    <div class="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">
                <div class="text-center border border-secondary rounded p-3">
                        <h1>{{post.title}}</h1>
                        <img src="{{ post.thumbnail_img.url }}" style="max-width:400px;" class="mb-3">
                        {{post.content|safe}}
                    
                </div>
                <hr>
                <form method='POST' enctype='multipart/form-data' id='likes_form'>
                    
                    {% csrf_token %}
                        <fieldset >
                            <input type="number" name="like_id" value="{{post.pk}}" style="display:none">
                            <input type="email" name="like_email" value="{{user.email}}" style="display:none">
                        </fieldset>
                        <div>
                            <button id="like" style="font-size:1.5em" class="btn btn-outline-primary" type="submit">Like</button> 
                            <p id="like_msg">{{likes.liked_users|first_person}} {{likes.liked_users|leni}}</p>
                        </div>
                </form>


                <hr>
                <h1>Comments</h1>
                <hr>
                <div>
                        <div>
                                <form method='POST' enctype='multipart/form-data' class="mb-3" id='comment_form'>
                                    <legend class='border-bottom mb-4 display-4'>Write a Comment</legend>
                                    {% csrf_token %}
                                        <fieldset >
                                            {{form|crispy}}
                                            <input type="number" name="id" value="{{post.pk}}" style="display:none">
                                        </fieldset>
                                        <div class="mt-3">
                                            <button class='btn btn-outline-info' type ='submit'>Comment</button>
                                        </div>
                                </form>
                        </div>
                        <div id="new_come">
                            </div>
                        {% for comment in comments %}
                            
                            
                            <div class="border border-secondary rounded m-3 pl-4 pt-2 pb-2" style="background-color:rgb(245, 245, 248);">
                                <div style="display:flex; justify-content:space-between;">
                                        <h3>{{comment.writer.first_name}} {{comment.writer.last_name}}</h3>
                                        <p style="font-size:0.9em">- {{comment.date_posted}}</p>
                                </div>    
                                <hr>
                                <p>{{comment.comment}}</p>
                            </div>
                        {% endfor %}
                
                </div>
        </div>
        <div class="col-md-1"></div>
    </div>
</div>
<script type="module">
    var outer = document.createElement("div");
    outer.classList.add("border");
    outer.classList.add("border-secondary");
    outer.classList.add("rounded");
    outer.classList.add("m-3");
    outer.classList.add("pl-4");
    outer.classList.add("pt-2");
    outer.classList.add("pb-2");
    outer.style.backgroundColor='rgb(245, 245, 248)';

    var inner = document.createElement("div");
    inner.style.display="flex";
    inner.style.justifyContent="space-between";

    var first_name="{{user.first_name}}";
    var last_name="{{user.last_name}}";
    var email="{{user.email}}";
    var id ="{{post.pk}}";

    var htag=document.createElement("h3");
    htag.innerHTML = first_name+" "+last_name;

    var hrtag=document.createElement("hr");
    var innerp=document.createElement("p");
    innerp.style.fontSize="0.9em";
    var outerp=document.createElement("p");

	let comment_form=document.getElementById('comment_form');
	comment_form.addEventListener('submit', function(event){
		event.preventDefault();
		fetch("{% url 'blog:create_comment' %}",{
			method: "POST",
			body : new FormData(comment_form)
		}).then(res=>res.json())
		.then((data)=>{
			if(data.hasOwnProperty('error'))
			{
				comment_form.reset();
			}
			else
			{
                
                var date_posted=data.date_posted;
                var comment= data.comment;
                innerp.innerHTML=date_posted;
                inner.appendChild(htag);
                inner.appendChild(innerp);
                outer.appendChild(inner);
                outer.appendChild(hrtag);
                outerp.innerHTML=comment;
                outer.appendChild(outerp);
                var container = document.getElementById('new_come');
                container.insertBefore(outer, container.firstChild);
                comment_form.reset();
			}
		}).catch(err=>console.log(err))
    })
    let likes_form= document.getElementById('likes_form');
    likes_form.addEventListener('submit', function(event){
        event.preventDefault();
        console.log('submitted');
        fetch("{% url 'blog:like_post' %}",{
            method:"POST",
            body: new FormData(likes_form)
        
        }).then(res=>res.json())
		.then((data)=>{
			document.getElementById('like_msg').innerText=data.message
		}).catch(err=>console.log(err))
    })
    
</script>

{% endblock %}