accounts/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='accounts'
urlpatterns = [
    path('',views.home,name='accounts_home'),
    path('register',views.register,name='register'),
    path('profile/',views.red_profile, name='red_profile'),
    path('profile/<int:id>',views.profile, name='profile'),
    path('login/',auth_views.LoginView.as_view(template_name ='accounts/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='accounts/logout.html'), name='logout'),
    
]

blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_views


app_name='blog'
urlpatterns = [
    path('',views.index, name='index'),
    path('home', views.home, name='home'),
    path('create_post',views.create_post, name='create_post'),
    path('post/<int:id>', views.post_detail, name='post_detail'),
    path('create_comment', views.create_comment, name='create_comment'),
    path('like_post', views.like_post, name='like_post'),

]

features/urls.py
from django.urls import path
from . import views


app_name='features'
urlpatterns = [
    path('users',views.users, name='users'),
    path('suggestions',views.suggestions, name='suggestions'),
    path('news',views.news, name='news'),
    path('announcement',views.announcement, name='announcement'),
]

social/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/',include('accounts.urls')),
    path('', include('blog.urls')),
    path('features/',include('features.urls')),
    url(r'^ckeditor/', include('ckeditor_uploader.urls')),

]

urlpatterns+= static(settings.MEDIA_URL, document_root =settings.MEDIA_ROOT)

accounts/models.py
from django.db import models
from django.contrib.auth.models import BaseUserManager, AbstractUser
from django.utils.translation import ugettext_lazy as _

class MyAccountManager(BaseUserManager):
    def create_user(self, email, first_name,last_name, mobile_number,  password=None, ):
        if not email:
            raise ValueError('Users must have an email address')
        if not first_name:
            raise ValueError('Users must have a first name')
        if not last_name:
            raise ValueError('Users must have a last name')
        if not mobile_number:
            raise ValueError('User must have a mobile Number')
        
        user = self.model(
            email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            mobile_number=mobile_number
            
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, email, password,first_name, last_name, mobile_number):
        user =self.create_user(
			email=self.normalize_email(email),
            first_name=first_name,
            last_name=last_name,
            mobile_number=mobile_number,
			password=password,
		)
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user

class User(AbstractUser):
    username=None
    mobile_number = models.CharField(max_length=30, unique=True, null=True)
    country = models.CharField(max_length=100, null=True)
    state = models.CharField(max_length=100, null=True)
    city = models.CharField(max_length=100, null=True)
    country_iso= models.CharField(max_length=10,null=True)
    profile_pic = models.ImageField(default='default2.jpg', upload_to='profile_pics')
    first_name = models.CharField(_('first name'), max_length=30)
    last_name = models.CharField(_('last name'), max_length=30)

    REQUIRED_FIELDS = ['first_name','last_name','mobile_number']
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    objects = MyAccountManager()

    def __str__(self):
	    return self.email

accounts/forms.py
from django import forms
from .models import User
from django.contrib.auth.forms import UserCreationForm
from django.utils.translation import ugettext_lazy as _
from django.core.exceptions import ValidationError


class UserRegisterForm (UserCreationForm):
    
    class Meta :
        model=User
        fields=['first_name','last_name','email','mobile_number','profile_pic', 'password1','password2']
    
    #check if mobile numbe doesnt contain character
    def clean_mobile_number(self):
        mobile_number = self.cleaned_data['mobile_number']
        for char in mobile_number:
            if char<'0' or char >'9':
                raise ValidationError(
                _('%(mobile_number)s is not a valid phone number'),
                params={'mobile_number': mobile_number},
                )
        return mobile_number

accounts/views.py
from django.shortcuts import render, redirect
from .forms import UserRegisterForm
from django.conf import settings
from django.http import HttpResponse, FileResponse, JsonResponse
from .models import User
from blog.models import Post

# Create your views here.

def home(request):
    return render(request,'accounts/home.html')

def register(request):

    if request.method=='POST':
        form = UserRegisterForm(request.POST, request.FILES)

        if form.is_valid :
            form.save()
            return redirect('blog:index')

    else:
        form=UserRegisterForm()
    
    return render(request, 'accounts/register.html', {'form':form})

def red_profile(request):
    id=request.user.pk
    return redirect('accounts:profile', id)

def profile(request,id):
    person=User.objects.filter(pk=id).first()
    posts= Post.objects.filter(author=person)
    if posts==None:
        posts=[]
    else:
        posts=posts.all()

    return render(request,'accounts/profile.html',{'person':person,'posts':posts})

accounts/templates/base.html
<!doctype html>
<html lang="en">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>SOCIAL</title>
  </head>
  <body>
        <nav class="navbar navbar-expand-lg navbar-light mb-4" style="background-color: #ca8eec; position: -webkit-sticky;
        position: sticky;top: 0; z-index:2">
                <a class="navbar-brand" href="{% url 'blog:index' %}" style="font-size:2.5em;" class="ml-4">SOCIAL</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                  <span class="navbar-toggler-icon"></span>
                </button>
              
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                  <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                      <a class="nav-link" href="{% url 'blog:home' %}" style="font-size:1.5em;">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link" href="{% url 'accounts:red_profile' %}" style="font-size:1.5em;">Profile</a>
                    </li>
                    <li class="nav-item dropdown">
                      <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" style="font-size:1.5em;" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        More
                      </a>
                      <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'features:users' %}" style="font-size:1.5em;">Users</a>
                        <a class="dropdown-item" href="#" style="font-size:1.5em;">Settings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'features:suggestions' %}" style="font-size:1.5em;">Suggestions</a>
                      </div>
                    </li>
                    <li class="nav-item">
                      <a class="nav-link disabled" href="#" style="font-size:1.5em;">Disabled</a>
                    </li>
                  </ul>
                  <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-secondary my-2 my-sm-0" type="submit" style="font-size:1.5em;">Search</button>
                  </form>


                  <ul class="navbar-nav">
                      {% if user.is_authenticated %}
                        <li class="nav-item active">
                          <a class="nav-link text-danger" href="{% url 'accounts:logout' %}" style="font-size:1.3em;">LOGOUT</a>
                        </li>
                        {% else %}
                        <li class="nav-item active">
                            <a class="nav-link" href="{% url 'accounts:login' %}" style="font-size:1.3em;">LOGIN</a>
                        </li>
                        <li class="nav-item active">
                          <a class="nav-link" href="{% url 'accounts:register' %}" style="font-size:1.3em;">REGISTER</a>
                        </li>
                        {% endif %}
                    </ul>
                </div>
              </nav>


    {% block content %}

    {% endblock %}



    <!-- Footer -->
<footer class="footer font-small stylish-color-dark pt-4 mt-4" style="background-color:rgb(29, 28, 28); color:beige;>

        <!-- Footer Links -->
        <div class="container text-center text-md-left">
      
          <!-- Grid row -->
          <div class="row">
      
            <!-- Grid column -->
            <div class="col-md-4 mx-auto">
      
              <!-- Content -->
              <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Footer Content</h5>
              <p>Here you can use rows and columns to organize your footer content. Lorem ipsum dolor sit amet,
                consectetur
                adipisicing elit.</p>
      
            </div>
            <!-- Grid column -->
      
            <hr class="clearfix w-100 d-md-none">
      
            <!-- Grid column -->
            <div class="col-md-2 mx-auto">
      
              <!-- Links -->
              <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
      
              <ul class="list-unstyled">
                <li>
                  <a href="#!">Link 1</a>
                </li>
                <li>
                  <a href="#!">Link 2</a>
                </li>

                </li>
              </ul>
      
            </div>
            <!-- Grid column -->
      
            <hr class="clearfix w-100 d-md-none">
      
            <!-- Grid column -->
            <div class="col-md-2 mx-auto">
      
              <!-- Links -->
              <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
      
              <ul class="list-unstyled">
                <li>
                  <a href="#!">Link 1</a>
                </li>
                <li>
                  <a href="#!">Link 2</a>
                </li>

                </li>
              </ul>
      
            </div>
            <!-- Grid column -->
      
            <hr class="clearfix w-100 d-md-none">
      
            <!-- Grid column -->
            <div class="col-md-2 mx-auto">
      
              <!-- Links -->
              <h5 class="font-weight-bold text-uppercase mt-3 mb-4">Links</h5>
      
              <ul class="list-unstyled">
                <li>
                  <a href="#!">Link 1</a>
                </li>
                <li>
                  <a href="#!">Link 2</a>
                </li>
            
              </ul>
      
            </div>
            <!-- Grid column -->
      
          </div>
          <!-- Grid row -->
      
        </div>
        <!-- Footer Links -->
      
        <hr>
      
        <!-- Call to action -->
        <ul class="list-unstyled list-inline text-center py-2">
          <li class="list-inline-item">
            <h5 class="mb-1">Register for free</h5>
          </li>
          <li class="list-inline-item">
            <a href="#!" class="btn btn-outline-primary btn-rounded">Sign up!</a>
          </li>
        </ul>
        <!-- Call to action -->
      
        <hr>
      
       
      </footer>
      <!-- Footer -->

    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>